# Generated by Django 5.2.5 on 2025-08-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_status_alter_listing_housing_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
